name: Deploy Docs Site

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - stage
          - prod
        default: stage
jobs:
  # Invoke reusable workflow file which is kept in a private repository
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docs
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: JELLYCLOUD-IO
          github_token: ${{ secrets.CI_CD_ACCESS_TOKEN }}
          repo: ops
          ref: main
          workflow_file_name: __docs_release_deploy.yml
          client_payload: '{"env":"${{ inputs.env }}","ref":"${{ github.ref }}"}'
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
