name: Deploy Docs Site

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - stage
          - prod
        default: stage
jobs:
  get-runner:
    uses: jellycloud-io/ops/.github/workflows/set_runner.yml@main
    secrets: inherit

  # Invoke reusable workflow file which is kept in a private repository
  run-build:
    needs: [get-runner]
    runs-on: ${{ fromJson(needs.get-runner.outputs.runner) }}
    steps:
      - name: Deploy Docs
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: JELLYCLOUD-IO
          github_token: ${{ secrets.CI_CD_ACCESS_TOKEN }}
          repo: ops
          ref: main
          workflow_file_name: __docs_release_deploy.yml
          client_payload: '{"env":"${{inputs.env}}"}'
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
